---
title: 'Final WebScraping'
output:
  pdf_document:
    fig_height: 3
    fig_width: 4.5
  html_document: default
word_document: default
editor_options: 
  chunk_output_type: console
---
  

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(rvest)
library(httr)
```
```{r}
listpage <- read_html("https://www.metacritic.com/browse/games/score/metascore/90day/ps4/filtered") #Titles URL
titlelist<- html_nodes(listpage, "#main .product_title a")#just titles 
titles<-html_text(titlelist) # as html
for(i in 1:length(titles)){
  titles[i]= str_sub(titles[i], 30, -54)#format of titles
}
i<-46
Full.df<-data.frame("Name"=1:length(titles), "Date of Release"=1:length(titles), "MetaScore"=1:length(titles), "Critics"=1:length(titles),"User Score"=1:length(titles) ,"Number of Reviews"=1:length(titles), "Genres"=1:length(titles),"Rating"=1:length(titles),"Also on"=length(titles))
for(i in 1:length(titles)){
  urltitle<-titles[i ]
  urltitle<-str_replace_all(urltitle,"&","")#process to change titles to url form
  urltitle<-str_replace_all(urltitle,":","")
  urltitle<-str_replace_all(urltitle,"  "," ")
  urltitle<-str_replace_all(urltitle," ","-")
  urltitle<-str_replace_all(urltitle,";","")
  urltitle<-str_replace_all(urltitle,"\\.","")
  urltitle<-str_replace_all(urltitle,"'","")
  urltitle<-str_replace_all(urltitle,"/","")
  url<-str_c("https://www.metacritic.com/game/playstation-4/",urltitle)#combines strings
  url<-tolower(url)#puts into lower case
  url<-read_html(url)#so this is the url needed for the individual titles
  data<-html_nodes(url,"h1")
  textdata<-html_text(data)
  Full.df[i,1]=textdata[1]
  data<- html_nodes(url,".release_data")#release date
  textdata<-html_text(data)
  Full.df[i,2]=textdata[1]
  data<- html_nodes(url,".game span")#green yellow and red have different .positivespan changing to .game span gets everything METASCORE
  textdata<-html_text(data)
  Full.df[i,3]=textdata[1]
  data<- html_nodes(url,".count a span")#Critic Count
  textdata<-html_text(data)
  Full.df[i,4]=textdata[1]#
  data<- html_nodes(url,".large")#USER SCORE
  textdata<-html_text(data)
  Full.df[i,5]=textdata[1]
  data<- html_nodes(url,".feature_userscore a")# Num of Users reviewed
  textdata<-html_text(data)
  Full.df[i,6]=textdata[2]
  data<- html_nodes(url,".product_genre")#Genre
  textdata<-html_text(data)
  Full.df[i,7]=textdata[1]
  data<- html_nodes(url,".product_rating .data")#Rating of Game ie T or M
  textdata<-html_text(data)
  Full.df[i,8]=textdata[1]# some games have no rating
  data<- html_nodes(url,".product_platforms")#Platform it's also on
  textdata<-html_text(data)
  Full.df[i,9]=textdata[1]
  print(i)#progress checker
}
```

```{r}
Final.df <- Full.df %>%
  mutate(Date.of.Release = str_sub(Date.of.Release, 50, 70), Genres = str_sub(Genres, 50, -1), Number.of.Reviews = str_sub(Number.of.Reviews, 1, -9), CrossPlatform = ifelse(is.na(Also.on)== FALSE, "Y", "N")#cleans up everything 
         )%>%
  select(-Also.on) %>%
  mutate(MetaScore = as.numeric(MetaScore), Critics = as.numeric(Critics), User.Score = as.numeric(User.Score), Number.of.Reviews = as.numeric(Number.of.Reviews))
Final.df$Date.of.Release = str_sub(Final.df$Date.of.Release,7,-4)#messed up on date post fix
Final.df$Date.of.Release = as.Date(Final.df$Date.of.Release,"%b %d, %Y")#into date format
write_rds(Final.df,"Final")#writes into rds file
```

